# Generated by Django 3.2.7 on 2021-09-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='edad',
            field=models.PositiveIntegerField(default=0, verbose_name=range(16, 80)),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(default='', max_length=30),
        ),
    ]
